kind: pipeline
name: Test & Build

steps:
  - name: build
    image: node:10
    commands:
      - yarn install --offline --non-interactive --frozen-lockfile
      - yarn lint
      - yarn build

  - name: build latest docker image
    image: plugins/docker
    settings:
      registry: eu.gcr.io
      repo: eu.gcr.io/quiet-mechanic-140114/no-code-demo
      tags:
        - ${DRONE_COMMIT_SHA:0:8}-${DRONE_BUILD_CREATED}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
